name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: utkarsh08122
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy snake animation
        uses: actions/deploy-pages@v5
        with:
          artifact_name: github-pages